# Usa una imagen base de Python
FROM python:3.9

# Establece el directorio de trabajo
WORKDIR /main

# Copia el archivo requirements.txt y lo instala
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copia el resto de los archivos del proyecto
COPY . .

# Expone el puerto 5000
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python", "main.py"]
